version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: nombredetubasededatos
      POSTGRES_USER: nombreusuario
      POSTGRES_PASSWORD: contraseña
    ports:
      - "5432:5432"
